### ISSUE TITLE
terser-webpack-plugin插件编译以后，包体积确实缩小了，但是sourceMap乱了，导致无法在微信小程序开发工具中直接debugger

### ISSUE THREAD

**Issue by Arthur-TYX** [CANntyield/taro-plugin-repository#2]
看源码显示sourceMap是默认开启的。并且我按官方文档，还写入了  enableSourceMap: true,sourceMapType: 'source-map',但是run dev:weapp的时候，依然无法在代码或者编辑器debugger

**Comment by CANntyield** [comment]
这个我使用的时候也没注意到，我已经不用这个去压缩主包了。你可以试试这个库里的esbuildMinify.js，需要先install esbuild-loader，这个打包速度会更快点，但我不确定能不能解决SourceMap的问题

**Comment by Arthur-TYX** [comment]
> 这个我使用的时候也没注意到，我已经不用这个去压缩主包了。你可以试试这个库里的esbuildMinify.js，需要先install esbuild-loader，这个打包速度会更快点，但我不确定能不能解决SourceMap的问题

好的 谢谢

**Comment by Arthur-TYX** [comment]
还有一个点，官方推荐的优化插件：npm install --save-dev thread-loader cache-loader taro-plugin-compiler-optimization

安装cache-loader就提示不兼容项目里的webpack5.x版本，但是我们项目又不能降webpack版本

**Comment by CANntyield** [comment]
1、把closeScssCache改为true
plugins: [
    ['taro-plugin-compiler-optimization', {
        closeScssCache: true, // 默认开启cache-loader缓存scss策略,若想关闭该策略改为true
    }]
]
2、你把taro-plugin-compiler-optimization中index.js拷贝到你项目里直接使用，然后把cache-loader相关的代码干掉就好了

**Comment by Arthur-TYX** [comment]
> 1、把closeScssCache改为true plugins: [ ['taro-plugin-compiler-optimization', { closeScssCache: true, // 默认开启cache-loader缓存scss策略,若想关闭该策略改为true }] ] 2、你把taro-plugin-compiler-optimization中index.js拷贝到你项目里直接使用，然后把cache-loader相关的代码干掉就好了

是的，我也是这么干的，这样改完确实可以用了。但是这个插件依赖的thread-loader，当node版本大于等于18.15编译就不通过，不兼容（我们又不能降低node版本）。所以最后我还是彻底放弃taro-plugin-compiler-optimization来优化了。。。

**Comment by CANntyield** [comment]
可以尝试升级thread-loader，看能不能兼容高版本node，如果不行的话那就没办法了.
